# Generated by Django 3.2.7 on 2021-09-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': (('autorizar_usuario', 'Permite autorizar el acceso a SGPA'), ('acceso_usuario', 'Permite el acceso a SGPA'), ('editar_usuario', 'Permite editar usuario'), ('eliminar_usuario', 'Permite eliminar usuario'))},
        ),
    ]
