# Generated by Django 3.2.7 on 2021-09-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='numSprints',
            field=models.IntegerField(default=0),
        ),
    ]
