# Generated by Django 3.2.7 on 2021-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
