# Generated by Django 3.2.7 on 2021-09-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_alter_proyecto_numsprints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado',
            field=models.CharField(default='En_cola', max_length=10),
        ),
    ]
