# Generated by Django 3.2.7 on 2021-09-16 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_userstory_prioridad'),
        ('proyectos', '0005_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprint',
            name='fechaFin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estado',
            field=models.CharField(choices=[('En_cola', 'En_cola'), ('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Finalizado', 'Finalizado')], default='En_cola', max_length=10),
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Product_Backlog', 'Product_Backlog'), ('Sprint_Backlog', 'Sprint_Backlog'), ('Do', 'Do'), ('To_Do', 'To_Do'), ('Done', 'Done')], max_length=16)),
                ('estado', models.CharField(choices=[('Vacio', 'Vacio'), ('Cargado', 'Cargado')], default='Vacio', max_length=8)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('numTareas', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('tareas', models.ManyToManyField(to='tareas.UserStory')),
            ],
        ),
    ]
