# Generated by Django 3.2.7 on 2021-10-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='posicion',
            field=models.IntegerField(null=True),
        ),
    ]
