# Generated by Django 3.2.7 on 2021-11-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0010_sprint_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='posicion',
            field=models.IntegerField(null=True),
        ),
    ]
