# Generated by Django 3.2.7 on 2021-11-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_backlog_posicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='tipo',
            field=models.CharField(choices=[('Product_Backlog', 'Product_Backlog'), ('Sprint_Backlog', 'Sprint_Backlog'), ('Doing', 'Doing'), ('To_Do', 'To_Do'), ('Done', 'Done')], max_length=16),
        ),
    ]
