# Generated by Django 3.2.7 on 2021-09-09 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0003_alter_sprint_estado'),
        ('usuarios', '0002_perfil_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=300)),
                ('estado', models.CharField(default='En_Cola', max_length=7)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaInicio', models.DateField(null=True)),
                ('fechaFin', models.DateField(null=True)),
                ('identificador', models.CharField(max_length=80, null=True)),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
                ('sprint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos.sprint')),
            ],
            options={
                'unique_together': {('identificador', 'sprint')},
            },
        ),
    ]
