# Generated by Django 3.2.7 on 2021-09-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_remove_backlog_tareas'),
        ('tareas', '0002_userstory_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='backlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='proyectos.backlog'),
        ),
    ]
