# Generated by Django 3.2.7 on 2021-11-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil_roles'),
        ('tareas', '0004_alter_userstory_desarrollador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='desarrollador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
